export const GETALLBOOKREQ     = "GETALLBOOKREQ";
export const GETALLBOOKSUCESS  = "GETALLBOOKSUCESS";
export const GETALLBOOKFAILURE = "GETALLBOOKFAILURE";


export const GETSINGLE_BOOK_REQUEST = "GETSINGLE_BOOK_REQUEST";
export const GETSINGLE_BOOK_SUCCESS = "GETSINGLE_BOOK_SUCCESS";
export const GETSINGLE_BOOK_FAILURE = "GETSINGLE_BOOK_FAILURE";


export const ADDTOCARTBOOKREQ     = "ADDTOCARTBOOKREQ";
export const ADDTOCARTBOOKUCESS  = "ADDTOCARTBOOKUCESS";
export const ADDTOCARTBOOKFAILURE = "ADDTOCARTBOOKFAILURE";



export const DELTEFROMCARTREQ     = "DELTEFROMCARTREQ";
export const DELTEFROMCARTUCESS   = "DELTEFROMCARTUCESS";
export const DELTEFROMCARTFAILURE = "DELTEFROMCARTFAILURE";


export const GETCARTDATAREQ     = "GETCARTDATAREQ";
export const GETCARTDATASUCESS  = "GETCARTDATASUCESS";
export const GETCARTDATAFAILURE = "GETCARTDATAFAILURE";

